# Generated by Django 5.2.6 on 2026-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passwd_changed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
