# Generated by Django 5.2.6 on 2026-09-21 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_usuario_passwd_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='plan_diferencial_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.plandiferencial'),
        ),
        migrations.AlterField(
            model_name='plandeestudio',
            name='asignatura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.asignatura'),
        ),
    ]
